// Fallback for using MaterialIcons on Android and web.

import { Colors } from '@/constants/Colors';
import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { SymbolViewProps, SymbolWeight } from 'expo-symbols';
import { ComponentProps } from 'react';
import { OpaqueColorValue, type StyleProp, type TextStyle } from 'react-native';

type IconMapping = Record<SymbolViewProps['name'], ComponentProps<typeof MaterialIcons>['name']>;
type IconSymbolName = keyof typeof MAPPING | string;

/**
 * Add your SF Symbols to Material Icons mappings here.
 * - see Material Icons in the [Icons Directory](https://icons.expo.fyi).
 * - see SF Symbols in the [SF Symbols](https://developer.apple.com/sf-symbols/) app.
 */
const MAPPING = {
  'house': 'home',
  'house.fill': 'home',
  'paperplane.fill': 'send',
  'chevron.left.forwardslash.chevron.right': 'code',
  'chevron.right': 'chevron-right',
  'magnifyingglass': 'search',
  'magnifyingglass.circle.fill': 'search',
  'calendar': 'event',
  'calendar.badge.clock': 'event',
  'calendar.day.timeline.left': 'event',
  'calendar.day.timeline.trailing': 'event',
  'clock': 'access-time',
  'scissors': 'content-cut',
  'scissors.badge.ellipsis': 'content-cut',
  'plus': 'add',
  'trash': 'delete',
  'star.fill': 'star',
  'star': 'star-border',
  'heart.fill': 'favorite',
  'heart': 'favorite-border',
  'person.fill': 'person',
  'person': 'person-outline',
  'person.circle.fill': 'person',
  'person.circle': 'person-outline',
  'book.pages.fill': 'book',
  'book.pages': 'book',
  'gear': 'settings',
  'bell': 'notifications',
  'bell.fill': 'notifications',
  'dollarsign.circle': 'attach-money',
  'location': 'location-on',
  'phone': 'phone',
  'envelope': 'email',
  'checkmark': 'check',
  'xmark': 'close',
  'pencil': 'edit',
  'camera': 'camera-alt',
  'photo': 'photo',
  'map': 'map',
  'list.bullet': 'list',
  'grid': 'grid-view',
  'slider.horizontal.3': 'tune',
  'filter': 'filter-list',
  'sort': 'sort',
  'arrow.up': 'keyboard-arrow-up',
  'arrow.down': 'keyboard-arrow-down',
  'arrow.left': 'keyboard-arrow-left',
  'arrow.right': 'keyboard-arrow-right',
  'chevron.up': 'keyboard-arrow-up',
  'chevron.down': 'keyboard-arrow-down',
  'chevron.left': 'keyboard-arrow-left',
  'info.circle': 'info',
  'exclamationmark.triangle': 'warning',
  'checkmark.circle': 'check-circle',
  'xmark.circle': 'cancel',
  'play.circle': 'play-circle-filled',
  'pause.circle': 'pause-circle-filled',
  'stop.circle': 'stop',
  'bookmark': 'bookmark-border',
  'bookmark.fill': 'bookmark',
  'share': 'share',
  'link': 'link',
  'copy': 'content-copy',
  'square.and.arrow.up': 'file-upload',
  'square.and.arrow.down': 'file-download',
  'doc.text': 'description',
  'folder': 'folder',
  'folder.fill': 'folder',
  'paperclip': 'attach-file',
  'mic': 'mic',
  'mic.fill': 'mic',
  'video': 'videocam',
  'video.fill': 'videocam',
  'speaker': 'volume-up',
  'speaker.slash': 'volume-off',
  'wifi': 'wifi',
  'wifi.slash': 'wifi-off',
  'battery.100': 'battery-full',
  'battery.75': 'battery-6-bar',
  'battery.50': 'battery-4-bar',
  'battery.25': 'battery-2-bar',
  'battery.0': 'battery-0-bar',
  'sun.max': 'wb-sunny',
  'moon': 'nightlight-round',
  'cloud': 'cloud',
  'cloud.rain': 'cloud-queue',
  'cloud.sun': 'wb-cloudy',
  'thermometer': 'thermostat',
  'drop': 'water-drop',
  'wind': 'air',
  'eye': 'visibility',
  'eye.slash': 'visibility-off',
  'lock': 'lock',
  'lock.open': 'lock-open',
  'key': 'vpn-key',
  'shield': 'security',
  'hand.raised': 'pan-tool',
  'hand.thumbsup': 'thumb-up',
  'hand.thumbsdown': 'thumb-down',
  'hand.point.up': 'back-hand',
  'hand.wave': 'waving-hand',
  'face.smiling': 'sentiment-very-satisfied',
  'face.dashed': 'sentiment-neutral',
  'face.frowning': 'sentiment-very-dissatisfied',
  'brain.head.profile': 'psychology',
  'brain': 'psychology',
  'heart.text.square': 'favorite',
  'lungs': 'air',
  'cross.case': 'medical-services',
  'pills': 'medication',
  'cross.fill': 'add',
  'cross': 'add',
  'minus': 'remove',
  'multiply': 'close',
  'divide': 'functions',
  'equal': 'drag-indicator',
  'percent': 'percent',
  'number': 'numbers',
  'textformat': 'format-color-text',
  'bold': 'format-bold',
  'italic': 'format-italic',
  'underline': 'format-underlined',
  'strikethrough': 'format-strikethrough',
  'text.alignleft': 'format-align-left',
  'text.aligncenter': 'format-align-center',
  'text.alignright': 'format-align-right',
  'text.alignjustify': 'format-align-justify',
  'list.number': 'format-list-numbered',
  'list.bullet.rectangle': 'format-list-bulleted',
  'quote.bubble': 'format-quote',
  'text.quote': 'format-quote',
  'text.cursor': 'text-fields',
  'cursorarrow': 'mouse',
  'hand.tap': 'touch-app',
  'hand.draw': 'gesture',
  'hand.point.left': 'back-hand',
  'hand.point.right': 'back-hand',
  'hand.point.down': 'back-hand',
  'hand.raised.fill': 'pan-tool',
  'hand.thumbsup.fill': 'thumb-up',
  'hand.thumbsdown.fill': 'thumb-down',
  'hand.point.up.fill': 'back-hand',
  'hand.wave.fill': 'waving-hand',
  'face.smiling.fill': 'sentiment-very-satisfied',
  'face.dashed.fill': 'sentiment-neutral',
  'face.frowning.fill': 'sentiment-very-dissatisfied',
  'brain.head.profile.fill': 'psychology',
  'brain.fill': 'psychology',
  'heart.text.square.fill': 'favorite',
  'lungs.fill': 'air',
  'cross.case.fill': 'medical-services',
  'pills.fill': 'medication',
  'cross.fill': 'add',
  'cross': 'add',
  'minus': 'remove',
  'multiply': 'close',
  'divide': 'functions',
  'equal': 'drag-indicator',
  'percent': 'percent',
  'number': 'numbers',
  'textformat': 'format-color-text',
  'bold': 'format-bold',
  'italic': 'format-italic',
  'underline': 'format-underlined',
  'strikethrough': 'format-strikethrough',
  'text.alignleft': 'format-align-left',
  'text.aligncenter': 'format-align-center',
  'text.alignright': 'format-align-right',
  'text.alignjustify': 'format-align-justify',
  'list.number': 'format-list-numbered',
  'list.bullet.rectangle': 'format-list-bulleted',
  'quote.bubble': 'format-quote',
  'text.quote': 'format-quote',
  'text.cursor': 'text-fields',
  'cursorarrow': 'mouse',
  'hand.tap': 'touch-app',
  'hand.draw': 'gesture',
  'hand.point.left': 'back-hand',
  'hand.point.right': 'back-hand',
  'hand.point.down': 'back-hand',
  'creditcard': 'credit-card',
  'creditcard.fill': 'credit-card',
  'questionmark.circle': 'help',
  'questionmark.circle.fill': 'help',
  'rectangle.portrait.and.arrow.right': 'exit-to-app',
  'schedule': 'schedule',
  'event-note': 'event-note',
  'content-cut': 'content-cut',
  'text.bubble': 'chat-bubble',
  'text.bubble.fill': 'chat-bubble',
  'plus.circle': 'add-circle',
  'plus.circle.fill': 'add-circle',
  'building.2': 'business',
  'building.2.fill': 'business',
  'wrench.and.screwdriver': 'build',
  'wrench.and.screwdriver.fill': 'build',
  'gearshape': 'settings',
  'gearshape.fill': 'settings',
  'lock.shield': 'security',
  'lock.shield.fill': 'security',
  'sparkles': 'auto-awesome',
  'leaf': 'eco',
  'leaf.fill': 'eco',
  'line.3.horizontal.decrease': 'filter-list',
  'star.lefthalf.fill': 'star-half',
} as IconMapping;

/**
 * An icon component that uses native SF Symbols on iOS, and Material Icons on Android and web.
 * This ensures a consistent look across platforms, and optimal resource usage.
 * Icon `name`s are based on SF Symbols and require manual mapping to Material Icons.
 */
export function IconSymbol({
  name,
  size = 24,
  color,
  style,
}: {
  name: IconSymbolName;
  size?: number;
  color?: string | OpaqueColorValue;
  style?: StyleProp<TextStyle>;
  weight?: SymbolWeight;
}) {
  // Si no se proporciona color, usar color de texto del tema claro
  const defaultColor = Colors.light.text;
  const iconColor = color || defaultColor;
  
  return <MaterialIcons color={iconColor} size={size} name={MAPPING[name]} style={style} />;
}
